public class Home2 {public static void main(String[] args){
    byte b=12;
    System.out.println(b);
    b=-127;
    System.out.println(b);
    b = 127;
    System.out.println(b);
    short s=-32000;
    System.out.println(s);
    s=32000;
    System.out.println(s);
    s=1000;
    System.out.println(s);
    int i= 121_312_312;
    System.out.println(i);
    i= -2032050209;
    System.out.println(i);
    i= 131_521_616;
    System.out.println(i);
    long l=1411511614000L;
    System.out.println(l);
    double d=17.124;
    System.out.println(d);
    d=17;
    System.out.println(d);
    d=-3.14;
    System.out.println(d);
    float f=3.125F;
    System.out.println(f);
    f=3F;
    System.out.println(f);
    f=-15F;
    System.out.println(f);
    char c=66;
    System.out.println(c);
    c=36;
    System.out.println(c);
    c=173;
    System.out.println(c);
    boolean m=(f>b);
    System.out.println(m);
    boolean m1=i>b;
    System.out.println(m1);
    boolean m2=d<f;
    System.out.println(m2);
}
}
